insert the playbook monitoring-zabbix-template.yml book with scs-template it was tested in train and should work in ussuri but we detected a bug :-(
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.zabbix.zabbix_template_payload_t83e8sut/ansible_community.zabbix.zabbix_template_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_template.py", line 751, in <module>
  File "/tmp/ansible_community.zabbix.zabbix_template_payload_t83e8sut/ansible_community.zabbix.zabbix_template_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_template.py", line 669, in main
  File "/tmp/ansible_community.zabbix.zabbix_template_payload_t83e8sut/ansible_community.zabbix.zabbix_template_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_template.py", line 669, in <genexpr>
TypeError: string indices must be integers
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_community.zabbix.zabbix_template_payload_t83e8sut/ansible_community.zabbix.zabbix_template_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_template.py\", line 751, in <module>\n  File \"/tmp/ansible_community.zabbix.zabbix_template_payload_t83e8sut/ansible_community.zabbix.zabbix_template_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_template.py\", line 669, in main\n  File \"/tmp/ansible_community.zabbix.zabbix_template_payload_t83e8sut/ansible_community.zabbix.zabbix_template_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_template.py\", line 669, in <genexpr>\nTypeError: string indices must be integers\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

which is tracked here

https://github.com/ansible-collections/community.zabbix/issues/258